### ISSUE TITLE
Latest Version Won't Remove From Plugin Store After Install

### ISSUE THREAD

**Issue by JamesStuder** [ChrisAdamsUK/OptionSetEditor#3]
XrmToolBox keeps showing the latest version in the plugin store.  Says installed version is 1.0.0.0 and latest version is 1.0.5.  After clicking to install latest version, it still shows that older version is installed.  Looking at the source code, it appears you need to update the last 2 lines of the assembly reference to be version 1.0.5.

**Comment by ChrisAdamsUK** [comment]
This is already the case. The source code hasn't been updated. The toolbox reads the assembly info to display the current version

**Comment by JamesStuder** [comment]
Right.  What I am saying is your code is wrong.  The assembly says 1.0.0 when the current version you say is 1.0.5.  This means the plugin always shows an update and never removes from the XrmToolBox store as being updated and when you open the app, the need to update dialog always appears.

**Comment by ChrisAdamsUK** [comment]
Yes, but the toolbox doesn't use this source code. It uses the compiled version which I publish to Nuget and is based on correct code.
At some point I will update the source code in here.

Others seem to be successfully installing the plugin. There was an issue with v1.4 where the plugin accidentally got moved outside the plugins folder in Nuget v1.5 fixed this.

Regards
Chris

**Comment by JamesStuder** [comment]
Yes, the plugin installs, but it is really annoying to always be in the store and saying not installed.  I ran into the same issue with my plugin(s).  You have to update the assembly info to match what you include in the nuget.  The version shown in the store is from the nuget version but once installed, it will report as not being updated because of the assembly version not matching.  They have to be in sync.  Check this link, it even says to make sure you update the assembly info. https://www.xrmtoolbox.com/documentation/for-developers/create-your-own-plugin-for-xrmtoolbox/

**Comment by ChrisAdamsUK** [comment]
That is what I am saying. It is already in sync I just havent pushed it to git hub yet.

On 8 Jan 2019 14:54, James E Studer <notifications@github.com> wrote:

Yes, the plugin installs, but it is really annoying to always be in the store and saying not installed. I ran into the same issue with my plugin(s). You have to update the assembly info to match what you include in the nuget. The version shown in the store is from the nuget version but once installed, it will report as not being updated because of the assembly version not matching. They have to be in sync. Check this link, it even says to make sure you update the assembly info. https://www.xrmtoolbox.com/documentation/for-developers/create-your-own-plugin-for-xrmtoolbox/

**Comment by mscottsewell** [comment]
This issue continues to exist - not sure why it was closed.
